### ISSUE TITLE
angular.min.js:107 TypeError: Cannot read property 'longDateFormat' of null

### ISSUE THREAD

**Issue by askie** [indrimuska/angular-moment-picker#21]
`<input locale="window.localStorage.lang" ng-model="stockIn.pre_in_time" moment-picker="stockIn.pre_in_time" type="text" class="input-xlarge" required>`

error when picked datetime :

`angular.min.js:107 TypeError: Cannot read property 'longDateFormat' of null
    at c (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:4579)
    at String.replace (native)
    at L (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:4650)
    at va (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:9797)
    at Aa (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:11147)
    at za (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:10886)
    at Ca (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:11581)
    at Da (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:11615)
    at a (http://192.168.0.121:4040/web/erp/bower_components/moment/min/moment-with-locales.min.js:1:202)
    at Object.fn (http://192.168.0.121:4040/web/erp/bower_components/angular-moment-picker/dist/angular-moment-picker.js:435:27)`

**Comment by askie** [comment]
how to init datetime ?

**Comment by indrimuska** [comment]
Hi @askie, you just need to initialize your model in your controller as a string:
```javascript
$scope.stockIn.pre_in_time = moment().format('L LTS');
// or
$scope.stockIn.pre_in_time = "04/16/2016 11:08:39 AM";
```
otherwise you can use `ng-init` directive like this:
```html
<div ng-init=" stockIn.pre_in_time = '04/16/2016 11:08:39 AM' ">
   <input ng-model="stockIn.pre_in_time" moment-picker="stockIn.pre_in_time">
</div>
```
